Fix user-module import
snowfallorg/lib pull request #109
Opened 2024-06-18 06:38 UTC by mtaku3

I was having an issue with user-module import, which is `home-manager.users.${user}` are set properly, but `snowfallorg.users.${user}.home.config` aren't.
This is a fix for it.

related: https://github.com/snowfallorg/lib/issues/104

2024-06-19 19:58 UTC, jakehamilton commented
Thanks for this! I need to test this out and verify things are working as expected with the rest of the system.

2024-10-28 14:00 UTC, AurelienConte commented
Any ETA on this ? @jakehamilton i think this would be cool if this can be checked since many issues are concerning problems about applying home manager configuration.

2024-10-28 16:22 UTC, jakehamilton commented
@AurelienConte thanks for the reminder! I will test it today and try to get things merged in if there aren't any issues :)

2024-10-28 17:21 UTC, jakehamilton requested changes

2024-10-28 17:21 UTC, jakehamilton commented on snowfall-lib/home/default.nix
> +                  sharedModules = optional config.snowfallorg.users.${user-name}.home.enable user-module;
This will include the user-specific module for all home-manager users. I don't think we can use this solution since it would break multi-user setups.

2025-01-27 14:45 UTC, closed without merging